include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - prefer_constructors_over_static_methods
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_lambdas
