name: hacker_news
description: A hacker news app created with flutter.
publish_to: 'none'
version: 0.1.7+12

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  hive_ce_flutter: ^2.3.1
  http: ^1.5.0
  intl: ^0.20.2
  lottie: ^3.3.1
  package_info_plus: ^8.3.1
  share_plus: ^11.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  web: 
    generate: true
  macos:
    generate: true
  remove_alpha_ios: true
  image_path: 'assets/app_icon.jpg'