name: hacker_news
description: A hacker news app created with flutter.
publish_to: 'none'
version: 0.1.1+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^10.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  intl: ^0.18.0
  meta: ^1.9.1
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  web: 
    generate: true
  macos:
    generate: true
  remove_alpha_ios: true
  image_path: 'assets/app_icon.jpg'