name: hacker_news
description: A hacker news app created with flutter.
publish_to: 'none'
version: 0.1.4+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^13.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  intl: ^0.18.0
  lottie: ^2.7.0
  meta: ^1.10.0
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  web: 
    generate: true
  macos:
    generate: true
  remove_alpha_ios: true
  image_path: 'assets/app_icon.jpg'