name: hacker_news
description: A hacker news app created with flutter.
publish_to: 'none'
version: 0.1.5+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  lottie: ^3.2.0
  meta: ^1.15.0
  package_info_plus: ^8.1.1
  share_plus: ^10.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  web: 
    generate: true
  macos:
    generate: true
  remove_alpha_ios: true
  image_path: 'assets/app_icon.jpg'