name: hacker_news
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  hive: ^2.2.3
  http: ^0.13.5
  meta: ^1.8.0
  path_provider: ^2.0.13
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

flutter:
  uses-material-design: true
