name: hacker_news
description: A hacker news app created with flutter.
publish_to: 'none'
version: 0.0.3+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^10.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  meta: ^1.9.1
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  uses-material-design: true
